# Generated by Django 5.0.7 on 2024-08-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_rename_description_organization_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='About',
            new_name='about',
        ),
    ]
