# Generated by Django 5.0.7 on 2024-08-06 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0005_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='razorpay_order_id',
        ),
    ]
