# Generated by Django 5.0.7 on 2024-08-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0006_delete_payment_remove_donation_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
